#Download base image python buster
FROM rocm/rocm-terminal
USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
ENV LD_LIBRARY_PATH=/opt/rocm/lib

RUN echo "/opt/rocm/opencl/lib/libamdocl64.so" >> /etc/OpenCL/vendors/amdocl64.icd

RUN apt-get update
RUN apt install -y apt-utils
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get install -y python3.8-dev && \
    apt-get install -y python3-pip && \
    apt-get install -y python3.8-tk && \
    apt-get install -y ocl-icd* opencl-headers &&\
    apt-get install -y libclfft* &&\
    apt-get install -y git &&\
    apt-get install -y pocl-opencl-icd

RUN apt-get install -y pkg-config
RUN apt-get install -y libhdf5-dev

RUN python3.8 -m pip install --upgrade pip

RUN python3.8 -m pip install cython
RUN python3.8 -m pip install mako
RUN python3.8 -m pip install pybind11
RUN python3.8 -m pip install pyopencl


RUN git clone https://github.com/geggo/gpyfft.git &&\
    python3.8 -m pip install gpyfft/. &&\
    python3.8 -m pip install pytest &&\
    python3.8 -m pip install pytest-cov &&\
    python3.8 -m pip install pylint &&\
    python3.8 -m pip install pylint_junit &&\
    python3.8 -m pip install pytest-integration

RUN mkdir /opt/pyqmri
